# Generated by Django 4.2.2 on 2023-06-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0005_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='postit/static/images/'),
        ),
    ]
