# Generated by Django 4.2.2 on 2023-06-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
